<div class="col-lg-4 col-xs-12 ">
					<a href="[field:arcurl/]" class="line">
						<img src="[field:litpic/]" />
						<div class="xin">
							<div class="time">
								<span>[field:pubdate function='strftime("%d",@me)'/]</span>
								<p>[field:pubdate function='strftime("%Y-%m",@me)'/]</p>
							</div>
							<div class="text">
								<h2>[field:title/]</h2>
								<p>[field:description function="cn_substr(@me,60)"/]</p>
							</div>
						</div>
					</a>
				</div>