<div class="new">
    			<a href="[field:arcurl/]">
	    			<div class="col-lg-2 col-xs-3 shijian">
	    				<h2>[field:pubdate function='strftime("%d",@me)'/]</h2>
	    				<p>[field:pubdate function='strftime("%Y-%m",@me)'/]</p>
	    				<p>[field:typelink/]</p>
	    			</div>
	    			<div class="col-lg-10 col-xs-9">
	    				<h2 class="title">[field:title/]</h2>
	    				<p class="text">[field:description/]</p>
	    			    <p class="num">浏览次数：[field:click/]</p>
	    			</div>
    			</a>
    		</div>