<div class="col-lg-3 col-xs-12 casepic">
					<div class="recent-work-wrap">
			          <a href="[field:arcurl/]">
			          <img class="img-responsive" src="[field:litpic/]" alt="[field:title/]">
				          <div class="overlay">
					            <div class="recent-work-inner">
					              <h3>[field:title/]</h3>
					            </div>
				          </div>
				       </a>
			        </div>
				</div>